<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Violas Group Presentation V1</title>
  <meta name="description" content="">
  <meta name="author" content="Joe, Jason, Pam">
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
  <link rel="stylesheet" href="libraries/frameworks/revealjs/css/reveal.min.css">
  <link rel="stylesheet" href="libraries/frameworks/revealjs/css/theme/default.css" id="theme">
  <link rel="stylesheet" href="libraries/highlighters/highlight.js/css/default.css" id="theme">
  <!--[if lt IE 9]>
  <script src="lib/js/html5shiv.js"></script>
  <![endif]-->  <link rel="stylesheet" href = "assets/css/ribbons.css">

</head>
<body>
  <div class="reveal">
    <div class="slides">
      <section class='' data-state='' id='slide-1'>
  
  <p>Violas Group Presentation </p>

<p>Guns Dataset from the &quot;AER&quot; Package</p>

<p>by Joe, Jason, &amp; Pam</p>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Review the Guns dataset from the &quot;AER&quot; package.</h2>
  <ul>
<li><strong>Dataset is a balanced panel of data on 50 US states, plus the District of Columbia (for a total of 51 states), by year for 1977 - 1999, and contains 1,173 observations on 13 variables. The variables are:</strong>

<ul>
<li><strong><em>state:</em></strong> factor indicating state.</li>
<li><strong><em>year:</em></strong> factor indicating year.</li>
<li><strong><em>violent:</em></strong> violent crime rate (incidents per 100,000 members of the population).</li>
<li><strong><em>murder:</em></strong> murder rate (incidents per 100,000).</li>
<li><strong><em>robbery:</em></strong> robbery rate (incidents per 100,000).</li>
<li><strong><em>prisoners:</em></strong> incarceration rate in the state in the previous year (sentenced prisoners per 100,000 residents;value for the previous year).</li>
<li><strong><em>afam:</em></strong> percent of state population that is African-American, ages 10 to 64.</li>
<li><strong><em>cauc:</em></strong> percent of state population that is Caucasian, ages 10 to 64.</li>
</ul></li>
</ul>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Review the Guns dataset from the &quot;AER&quot;&quot; package.</h2>
  <ul>
<li><strong>The variables are: (con&#39;t):</strong>

<ul>
<li><strong><em>male:</em></strong> percent of state population that is male, ages 10 to 29.</li>
<li><strong><em>population:</em></strong> state population, in millions of people.</li>
<li><strong><em>income:</em></strong> real per capita personal income in the state (US dollars).</li>
<li><strong><em>density:</em></strong> population per square mile of land area, divided by 1,000.</li>
<li><strong><em>law:</em></strong> factor. Does the state have a shall carry law in effect in that year?</li>
</ul></li>
</ul>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Objective: Using the data collected see if we can Identify a model that helps best predict the violence rate.</h2>
  
</section>
<section class='class' data-state='' id='Slide'>
  <h2>Review the structure of the Guns data</h2>
  <pre><code>## &#39;data.frame&#39;:    1173 obs. of  13 variables:
##  $ year      : Factor w/ 23 levels &quot;1977&quot;,&quot;1978&quot;,..: 1 2 3 4 5 6 7 8 9 10 ...
##  $ violent   : num  414 419 413 448 470 ...
##  $ murder    : num  14.2 13.3 13.2 13.2 11.9 10.6 9.2 9.4 9.8 10.1 ...
##  $ robbery   : num  96.8 99.1 109.5 132.1 126.5 ...
##  $ prisoners : int  83 94 144 141 149 183 215 243 256 267 ...
##  $ afam      : num  8.38 8.35 8.33 8.41 8.48 ...
##  $ cauc      : num  55.1 55.1 55.1 54.9 54.9 ...
##  $ male      : num  18.2 18 17.8 17.7 17.7 ...
##  $ population: num  3.78 3.83 3.87 3.9 3.92 ...
##  $ income    : num  9563 9932 9877 9541 9548 ...
##  $ density   : num  0.0746 0.0756 0.0762 0.0768 0.0772 ...
##  $ state     : Factor w/ 51 levels &quot;Alabama&quot;,&quot;Alaska&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ law       : Factor w/ 2 levels &quot;no&quot;,&quot;yes&quot;: 1 1 1 1 1 1 1 1 1 1 ...
</code></pre>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Review the summary of the Guns data</h2>
  <pre><code>##       year        violent           murder          robbery      
##  1977   : 51   Min.   :  47.0   Min.   : 0.200   Min.   :   6.4  
##  1978   : 51   1st Qu.: 283.1   1st Qu.: 3.700   1st Qu.:  71.1  
##  1979   : 51   Median : 443.0   Median : 6.400   Median : 124.1  
##  1980   : 51   Mean   : 503.1   Mean   : 7.665   Mean   : 161.8  
##  1981   : 51   3rd Qu.: 650.9   3rd Qu.: 9.800   3rd Qu.: 192.7  
##  1982   : 51   Max.   :2921.8   Max.   :80.600   Max.   :1635.1  
##  (Other):867                                                     
##    prisoners           afam              cauc            male      
##  Min.   :  19.0   Min.   : 0.2482   Min.   :21.78   Min.   :12.21  
##  1st Qu.: 114.0   1st Qu.: 2.2022   1st Qu.:59.94   1st Qu.:14.65  
##  Median : 187.0   Median : 4.0262   Median :65.06   Median :15.90  
##  Mean   : 226.6   Mean   : 5.3362   Mean   :62.95   Mean   :16.08  
##  3rd Qu.: 291.0   3rd Qu.: 6.8507   3rd Qu.:69.20   3rd Qu.:17.53  
##  Max.   :1913.0   Max.   :26.9796   Max.   :76.53   Max.   :22.35  
##                                                                    
##    population          income         density                 state     
##  Min.   : 0.4027   Min.   : 8555   Min.   : 0.000707   Alabama   :  23  
##  1st Qu.: 1.1877   1st Qu.:11935   1st Qu.: 0.031911   Alaska    :  23  
##  Median : 3.2713   Median :13402   Median : 0.081569   Arizona   :  23  
##  Mean   : 4.8163   Mean   :13725   Mean   : 0.352038   Arkansas  :  23  
##  3rd Qu.: 5.6856   3rd Qu.:15271   3rd Qu.: 0.177718   California:  23  
##  Max.   :33.1451   Max.   :23647   Max.   :11.102120   Colorado  :  23  
##                                                        (Other)   :1035  
##   law     
##  no :888  
##  yes:285  
##           
##           
##           
##           
## 
</code></pre>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Visualization of the Data</h2>
  <p><img src="figure/fig1-1.png" title="plot of chunk fig1" alt="plot of chunk fig1" style="display: block; margin: auto;" /></p>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Analysis from Visualizing the Data</h2>
  <p><strong>The violent variable does not appear to be normally distributed</strong></p>

<ul>
<li>Histogram, the distribution of the violent variable deviates from the normal distribution

<ul>
<li>Doesn&#39;t adhere to the blue QQ-line on the the QQ-Plot. </li>
<li>Violent variable is skewed to the right (positively) and the mean (503.074) &gt; median (443)</li>
</ul></li>
<li>Sort Plot there appears to be a few clusters on the right side of the plot, where the violent crime rate is high</li>
<li>Consider the use of a log() transformation on the <em>violent</em> variable 

<ul>
<li>Could Reduce the skewness</li>
<li>Potentially make it easier to interpret whether or not a relationship exist between variables that might not have otherwise been obvious.</li>
</ul></li>
</ul>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Examine the Scatterplot</h2>
  <p><img src="figure/fig2-1.png" title="plot of chunk fig2" alt="plot of chunk fig2" style="display: block; margin: auto;" /></p>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Analysis of the Scatterplot</h2>
  <ul>
<li>The variables murder and robbery have the strongest positive linear relationship with the violent crime rate, with a correlation value of 0.827 and 0.907

<ul>
<li>Considering these variables are components of the violent crime rate, we expected there to be high correlation values</li>
<li>These variables are more of a subcategory of violent crimes and therefore aren&#39;t good predictors for a linear model</li>
</ul></li>
<li>Other variables that showed a high correlation value were prisoners (0.703), density (0.665), afam (0.57), cauc(-0.573), and income (0.408)

<ul>
<li>The law variable was also a good indicator because the box plot showed that on average states that have a shall carry law in effect have a lower violent crime rate as well as as a lower murder and robbery rate.</li>
</ul></li>
</ul>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Original Model (mOrig): Fitted Plot and Residuals vs. Fitted</h2>
  <p><strong>mOrig = lm(violent~., data = Guns)</strong>  </p>

<p><img src="figure/fig3-1.png" title="plot of chunk fig3" alt="plot of chunk fig3" style="display: block; margin: auto;" /></p>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Analysis of the Original Model (mOrig)</h2>
  <p><strong>mOrig = lm(violent~., data = Guns)</strong></p>

<ul>
<li>The Fit Plot shows that the actual values fluctuate fairly significantly from the fitted values(pink reference line)</li>
<li>The Residual plot shows that a majority of the observed values fall within +/-500 of the fitted values

<ul>
<li>This could be considered a substantial deviation from the fitted values</li>
<li>Next lets examine if a log transformation or box-cox transformation would be useful</li>
</ul></li>
</ul>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Log Transformation Model (mLog): Fitted Plot and Residuals vs. Fitted</h2>
  <p><strong>mLog &lt;- lm(log(violent)~., data = Guns)</strong></p>

<p><img src="figure/fig4-1.png" title="plot of chunk fig4" alt="plot of chunk fig4" style="display: block; margin: auto;" /></p>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Analysis of the Log Transformation Model (mLog)</h2>
  <p><strong>mLog &lt;- lm(log(violent)~., data = Guns)</strong></p>

<ul>
<li>The Log Transformed Fit Plot shows that the actual values fluctuate from the fitted values(pink reference line), similar to the previous model (mOrig)</li>
<li>The Log Transformed Fit Plot vs Residual Plot is easier to read than the previous model (mOrig)

<ul>
<li>Y-axis, which shows the .resid is shown in Z-scores with a majority of the data falling between +/- 1 standard deviations from the mean</li>
<li>Using the log transformation of the violent variable makes it easier to interpret the data</li>
</ul></li>
</ul>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Box-Cox Transformation Model (mBC): Fitted Plot and Residuals vs. Fitted</h2>
  <p><strong>mBC &lt;- lm(violent<sup>lam</sup> ~ ., Guns)</strong>    </p>

<p><img src="figure/fig5-1.png" title="plot of chunk fig5" alt="plot of chunk fig5" style="display: block; margin: auto;" /></p>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Analysis of the Box-Cox Transformation Model (mBC)</h2>
  <p><strong>mBC &lt;- lm(violent<sup>lam</sup> ~ ., Guns)</strong> </p>

<pre><code>## Estimated transformation parameter 
##        Y1 
## 0.6022324
</code></pre>

<ul>
<li>The Box-Cox Transformed Fit Plot shows that the actual values fluctuate from the fitted values (Blue reference line), similar to the previous two model (mOrig) and (mLog), with the exception that the blue fitted line stems from a quadratic function compared to a linear model.</li>
<li>The Box-Cox Transformed Fit Plot vs Residual Plot is easier to read than the original model (mOrig), but not the Log Transformation model (mLog).

<ul>
<li>Y-axis, which shows the .resid is shown in Z-scores with a majority of the data falling between +/- 5 standard deviations from the mean</li>
</ul></li>
</ul>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Detecting Non Normality with Normal QQ-plots</h2>
  <p><img src="figure/fig6-1.png" title="plot of chunk fig6" alt="plot of chunk fig6" style="display: block; margin: auto;" /></p>

<p><strong>All plots are fairly similar, but the Box-Cox Transformed model appears to fit the best.</strong></p>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Normal Distribution with Histogram Plots</h2>
  <p><img src="figure/fig7-1.png" title="plot of chunk fig7" alt="plot of chunk fig7" style="display: block; margin: auto;" />
<strong>The residuals of the Box-Cox Transformed model appears to be the most normally distributed</strong></p>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Shapiro test of Normality</h2>
  <pre><code>##         Shapiro(mOrig) Shapiro(mLog) Shapiro(mBC)
## W         9.702328e-01  9.772737e-01 9.866434e-01
## p-value   8.514298e-15  1.292530e-12 6.980302e-09
</code></pre>

<ul>
<li>The Shapiro-Wilk test indicates the Pearson correlation between the residuals and the normal quantiles, W is equal to:

<ul>
<li>0.97023 untransformed model</li>
<li>0.97727 log-transformed model</li>
<li>0.98664 box-cox transformed model</li>
</ul></li>
</ul>

<p><strong>Based on our analysis, we will look at the Box-Cox transformed model (mBC) and log transformed model (mLog) further using a Stepwise Regression</strong></p>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Stepwise Regression Box Cox Model</h2>
  <h1></h1>

<pre><code>## Start:  AIC=2239.81
## violent^lam ~ year + murder + robbery + prisoners + afam + cauc + 
##     male + population + income + density + state + law
## 
##              Df Sum of Sq   RSS    AIC
## - cauc        1         0  6872 2237.8
## - density     1         0  6873 2237.9
## - afam        1         6  6879 2238.9
## - population  1         7  6879 2239.0
## - income      1         8  6880 2239.2
## &lt;none&gt;                     6872 2239.8
## - law         1        78  6950 2251.0
## - male        1       100  6972 2254.7
## - murder      1       132  7005 2260.2
## - prisoners   1       218  7090 2274.4
## - year       22      1632  8504 2445.7
## - robbery     1      4594 11467 2838.3
## - state      50     33830 40702 4226.3
## 
## Step:  AIC=2237.81
## violent^lam ~ year + murder + robbery + prisoners + afam + male + 
##     population + income + density + state + law
## 
##              Df Sum of Sq   RSS    AIC
## - density     1         0  6873 2235.9
## - population  1         8  6880 2237.1
## - income      1         8  6881 2237.2
## &lt;none&gt;                     6872 2237.8
## - afam        1        16  6888 2238.5
## - law         1        78  6951 2249.1
## - murder      1       133  7006 2258.3
## - male        1       194  7066 2268.4
## - prisoners   1       231  7104 2274.6
## - year       22      1825  8697 2470.0
## - robbery     1      4595 11467 2836.4
## - state      50     33910 40782 4226.6
## 
## Step:  AIC=2235.88
## violent^lam ~ year + murder + robbery + prisoners + afam + male + 
##     population + income + state + law
## 
##              Df Sum of Sq   RSS    AIC
## - population  1         7  6880 2235.1
## - income      1         9  6882 2235.4
## &lt;none&gt;                     6873 2235.9
## - afam        1        23  6896 2237.8
## - law         1        79  6952 2247.3
## - murder      1       136  7009 2256.9
## - male        1       193  7066 2266.4
## - prisoners   1       390  7263 2298.6
## - year       22      1825  8698 2468.1
## - robbery     1      4594 11467 2834.4
## - state      50     43238 50111 4466.2
## 
## Step:  AIC=2235.13
## violent^lam ~ year + murder + robbery + prisoners + afam + male + 
##     income + state + law
## 
##             Df Sum of Sq   RSS    AIC
## - income     1         9  6889 2234.6
## &lt;none&gt;                    6880 2235.1
## - afam       1        18  6898 2236.2
## - law        1        78  6958 2246.4
## - murder     1       130  7010 2255.0
## - male       1       199  7080 2266.6
## - prisoners  1       452  7332 2307.8
## - year      22      1849  8729 2470.3
## - robbery    1      4637 11517 2837.4
## - state     50     47934 54814 4569.5
## 
## Step:  AIC=2234.63
## violent^lam ~ year + murder + robbery + prisoners + afam + male + 
##     state + law
## 
##             Df Sum of Sq   RSS    AIC
## &lt;none&gt;                    6889 2234.6
## - afam       1        15  6904 2235.1
## - law        1        89  6978 2247.7
## - murder     1       172  7061 2261.5
## - male       1       206  7095 2267.2
## - prisoners  1       455  7344 2307.7
## - year      22      1844  8733 2468.9
## - robbery    1      4688 11577 2841.6
## - state     50     48242 55131 4574.2
</code></pre>

<p>From the stepwise regression of the Box Cox Model we see that cauc, density, and income should be removed from the data to create a globally optimal model</p>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Shapiro test of Normality</h2>
  <h2>Stepwise Regression Log Model</h2>

<h1></h1>

<pre><code>## Start:  AIC=-4785.25
## log(violent) ~ year + murder + robbery + prisoners + afam + cauc + 
##     male + population + income + density + state + law
## 
##              Df Sum of Sq     RSS     AIC
## - murder      1     0.000  17.224 -4787.2
## - density     1     0.007  17.231 -4786.8
## - population  1     0.007  17.231 -4786.8
## - income      1     0.008  17.232 -4786.7
## - afam        1     0.018  17.242 -4786.0
## &lt;none&gt;                     17.224 -4785.3
## - cauc        1     0.043  17.267 -4784.3
## - prisoners   1     0.124  17.348 -4778.9
## - law         1     0.151  17.375 -4777.0
## - male        1     0.258  17.482 -4769.8
## - year       22     3.406  20.630 -4617.6
## - robbery     1     3.484  20.708 -4571.2
## - state      50   117.192 134.416 -2475.2
## 
## Step:  AIC=-4787.24
## log(violent) ~ year + robbery + prisoners + afam + cauc + male + 
##     population + income + density + state + law
## 
##              Df Sum of Sq     RSS     AIC
## - density     1     0.007  17.231 -4788.8
## - population  1     0.007  17.231 -4788.8
## - income      1     0.008  17.232 -4788.7
## - afam        1     0.019  17.243 -4787.9
## &lt;none&gt;                     17.224 -4787.2
## - cauc        1     0.043  17.268 -4786.3
## - prisoners   1     0.130  17.354 -4780.4
## - law         1     0.151  17.375 -4779.0
## - male        1     0.260  17.484 -4771.7
## - year       22     3.562  20.786 -4610.8
## - robbery     1     4.187  21.411 -4534.0
## - state      50   117.213 134.437 -2477.0
## 
## Step:  AIC=-4788.78
## log(violent) ~ year + robbery + prisoners + afam + cauc + male + 
##     population + income + state + law
## 
##              Df Sum of Sq     RSS     AIC
## - population  1     0.008  17.239 -4790.2
## - income      1     0.011  17.242 -4790.0
## - afam        1     0.015  17.246 -4789.8
## &lt;none&gt;                     17.231 -4788.8
## - cauc        1     0.047  17.278 -4787.6
## - law         1     0.154  17.385 -4780.3
## - male        1     0.256  17.486 -4773.5
## - prisoners   1     0.314  17.545 -4769.6
## - year       22     3.569  20.800 -4612.0
## - robbery     1     4.209  21.440 -4534.4
## - state      50   147.152 164.383 -2243.1
## 
## Step:  AIC=-4790.21
## log(violent) ~ year + robbery + prisoners + afam + cauc + male + 
##     income + state + law
## 
##             Df Sum of Sq     RSS     AIC
## - income     1     0.014  17.253 -4791.3
## - afam       1     0.017  17.257 -4791.0
## &lt;none&gt;                    17.239 -4790.2
## - cauc       1     0.067  17.307 -4787.6
## - law        1     0.158  17.397 -4781.5
## - male       1     0.249  17.488 -4775.4
## - prisoners  1     0.306  17.545 -4771.6
## - year      22     3.569  20.809 -4613.5
## - robbery    1     4.210  21.449 -4535.9
## - state     50   170.164 187.404 -2091.3
## 
## Step:  AIC=-4791.29
## log(violent) ~ year + robbery + prisoners + afam + cauc + male + 
##     state + law
## 
##             Df Sum of Sq     RSS     AIC
## - afam       1     0.013  17.266 -4792.4
## &lt;none&gt;                    17.253 -4791.3
## - cauc       1     0.058  17.311 -4789.4
## - law        1     0.180  17.432 -4781.1
## - male       1     0.287  17.540 -4773.9
## - prisoners  1     0.324  17.576 -4771.5
## - year      22     3.568  20.821 -4614.8
## - robbery    1     4.201  21.453 -4537.7
## - state     50   171.726 188.979 -2083.5
## 
## Step:  AIC=-4792.39
## log(violent) ~ year + robbery + prisoners + cauc + male + state + 
##     law
## 
##             Df Sum of Sq     RSS     AIC
## &lt;none&gt;                    17.266 -4792.4
## - cauc       1     0.072  17.338 -4789.5
## - law        1     0.176  17.442 -4782.5
## - prisoners  1     0.348  17.614 -4771.0
## - male       1     0.576  17.842 -4755.9
## - year      22     4.015  21.281 -4591.1
## - robbery    1     4.209  21.475 -4538.5
## - state     50   173.317 190.583 -2075.6
</code></pre>

<p>From the stepwise regression of the Log Model we see that murder, density, population, income, and afam should be removed from the data to create a globally optimal model</p>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Compare Coefficients of the three models</h2>
  <h1></h1>

<pre><code>## Calls:
## 1: lm(formula = violent^lam ~ ., data = Guns)
## 2: lm(formula = violent^lam ~ year + murder + robbery + prisoners + 
##   afam + male + state + law, data = Guns)
## 3: lm(formula = log(violent) ~ year + robbery + prisoners + cauc + 
##   male + state + law, data = Guns)
## 
##                            Model 1  Model 2  Model 3
## (Intercept)                  11.31    11.56     4.29
## year1978                    0.8856   0.9553   0.0518
## year1979                     2.325    2.389    0.133
## year1980                     2.649    2.671    0.155
## year1981                     2.410    2.450    0.143
## year1982                     2.567    2.602    0.139
## year1983                     2.323    2.391    0.125
## year1984                     3.259    3.418    0.172
## year1985                     4.141    4.346    0.219
## year1986                     5.328    5.580    0.285
## year1987                     5.461    5.750    0.293
## year1988                     6.410    6.742    0.342
## year1989                     6.986    7.357    0.381
## year1990                     8.930    9.295    0.463
## year1991                     9.552    9.901    0.496
## year1992                     10.32    10.71     0.53
## year1993                    10.693   11.092    0.552
## year1994                    10.345   10.775    0.544
## year1995                     9.955   10.407    0.539
## year1996                     8.936    9.422    0.499
## year1997                     8.898    9.434    0.498
## year1998                     8.084    8.690    0.463
## year1999                     6.983    7.626    0.415
## murder                       0.152    0.161         
## robbery                    0.04985  0.04963  0.00137
## prisoners                 0.009925 0.010603 0.000243
## afam                        -0.419   -0.337         
## cauc                      -0.00345           0.00745
## male                        1.1242   1.1490   0.0637
## population                   0.148                  
## income                    0.000135                  
## density                     -0.354                  
## stateAlaska                 1.2105   1.5584  -0.0471
## stateArizona              -0.53089 -0.00311 -0.00699
## stateArkansas               -3.571   -3.556   -0.171
## stateCalifornia             -0.905    3.402    0.116
## stateColorado               -4.312   -3.369   -0.225
## stateConnecticut            -9.308   -8.101   -0.345
## stateDelaware              -0.4309  -0.2769  -0.0501
## stateDistrict of Columbia    3.678   -0.974    0.108
## stateFlorida                 9.819   11.711    0.465
## stateGeorgia               -2.0548  -1.6136  -0.0334
## stateHawaii                 -7.673   -8.697   -0.529
## stateIdaho                 -11.396  -11.064   -0.681
## stateIllinois                1.080    3.006    0.131
## stateIndiana                -7.291   -6.282   -0.327
## stateIowa                  -12.812  -11.991   -0.744
## stateKansas                 -7.503   -6.869   -0.356
## stateKentucky              -10.550  -10.055   -0.531
## stateLouisiana               4.418    4.261    0.199
## stateMaine                  -17.05   -16.48    -1.14
## stateMaryland                3.047    3.596    0.175
## stateMassachusetts          0.7647   2.1315   0.0136
## stateMichigan              -0.8238   0.6026   0.0356
## stateMinnesota             -13.513  -12.275   -0.704
## stateMississippi            -7.395   -8.024   -0.355
## stateMissouri              -2.3594  -1.5114  -0.0387
## stateMontana               -15.605  -15.365   -0.995
## stateNebraska               -10.19    -9.57    -0.58
## stateNevada                -2.6702  -2.2268  -0.0247
## stateNew Hampshire           -19.2    -18.3     -1.3
## stateNew Jersey             -5.283   -3.922   -0.117
## stateNew Mexico              8.059    8.094    0.226
## stateNew York              -3.5053  -0.6257   0.0611
## stateNorth Carolina        -1.4529  -0.9100  -0.0674
## stateNorth Dakota            -25.0    -24.6     -2.0
## stateOhio                    -9.26    -7.54    -0.31
## stateOklahoma               -3.220   -2.972   -0.141
## stateOregon                 -3.062   -2.247   -0.124
## statePennsylvania          -10.256   -8.189   -0.355
## stateRhode Island           -7.291   -6.984   -0.388
## stateSouth Carolina         10.383   10.077    0.321
## stateSouth Dakota           -16.97   -16.74    -1.13
## stateTennessee             -1.4840  -0.9172  -0.0457
## stateTexas                  -5.871   -3.514   -0.116
## stateUtah                  -13.091  -12.713   -0.734
## stateVermont                 -18.9    -18.4     -1.3
## stateVirginia              -12.078  -11.272   -0.551
## stateWashington             -4.343   -3.201   -0.199
## stateWest Virginia         -15.506  -15.137   -0.959
## stateWisconsin             -16.876  -15.811   -0.903
## stateWyoming               -10.731  -10.255   -0.638
## lawyes                     -1.0851  -1.1424  -0.0506
</code></pre>

<p>As you can see the larger model model mBC has larger standard errors then the smaller model mBCStep, which has gone through the stepwise regression</p>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>P-Value of the Partial F-test Box Cox Model and Stepwise Box Cox Model</h2>
  <h1></h1>

<pre><code>## Analysis of Variance Table
## 
## Model 1: violent^lam ~ year + murder + robbery + prisoners + afam + male + 
##     state + law
## Model 2: violent^lam ~ year + murder + robbery + prisoners + afam + cauc + 
##     male + population + income + density + state + law
##   Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
## 1   1094 6889.0                           
## 2   1090 6872.4  4    16.557 0.6565 0.6224
</code></pre>

<p><strong>The results produced by the anova function show a non-significant result (p-value = 0.6224).  Therefore we should reject the Box-Cox transformed larger model (mBC) and move forward with the Box-Cox transformed smaller model (mBCStep).</strong></p>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>P-Value of the Partial F-test Log Model and Stepwise Log Model</h2>
  <pre><code>## Analysis of Variance Table
## 
## Model 1: log(violent) ~ year + robbery + prisoners + cauc + male + state + 
##     law
## Model 2: log(violent) ~ year + murder + robbery + prisoners + afam + cauc + 
##     male + population + income + density + state + law
##   Res.Df    RSS Df Sum of Sq     F Pr(&gt;F)
## 1   1095 17.266                          
## 2   1090 17.224  5  0.042034 0.532 0.7522
</code></pre>

<p><strong>The results produced by the anova function show a non-significant result (p-value = 0.7522).  Therefore we should reject the log transformed larger model (mLog) and move forward with the log transformed smaller model (mLogStep).</strong></p>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Checking for any influential points that are controlling the results</h2>
  <p><img src="figure/mfig8-1.png" title="plot of chunk mfig8" alt="plot of chunk mfig8" style="display: block; margin: auto;" /></p>

<pre><code>##         StudRes        Hat       CookD
## 185   0.4156464 0.25978614 0.000731069
## 189  -5.0794642 0.25204347 0.102420286
## 195   3.9512822 0.13445287 0.028833267
## 207   0.4733689 0.29029093 0.001105054
## 1127  4.8407145 0.06827768 0.020271504
</code></pre>

<p>Although point 189 seems large, both the CookD and Hat value are low so this varaible isn&#39;t controlling the results</p>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Transformation Check</h2>
  <p><img src="figure/fig9-1.png" alt="plot of chunk fig9"></p>

<p><strong>After looking at the scaled scatterplot of that data we determine that cauc needs to be transformed</strong></p>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Stepwise regression with cauc normalized with log</h2>
  <h1></h1>

<pre><code>## Start:  AIC=9240.41
## violent ~ year + murder + robbery + prisoners + afam + log(cauc) + 
##     male + population + income + density + state + law
## 
##              Df Sum of Sq      RSS     AIC
## - density     1       236  2685757  9238.5
## - log(cauc)   1       335  2685857  9238.6
## &lt;none&gt;                     2685522  9240.4
## - income      1      5124  2690646  9240.6
## - afam        1      6355  2691877  9241.2
## - male        1     18702  2704223  9246.5
## - population  1     24164  2709685  9248.9
## - law         1     26090  2711611  9249.7
## - prisoners   1    177230  2862751  9313.4
## - murder      1    332563  3018084  9375.3
## - year       22    502422  3187943  9397.6
## - robbery     1   3052545  5738066 10129.0
## - state      50   8884729 11570250 10853.6
## 
## Step:  AIC=9238.51
## violent ~ year + murder + robbery + prisoners + afam + log(cauc) + 
##     male + population + income + state + law
## 
##              Df Sum of Sq      RSS     AIC
## - log(cauc)   1       219  2685976  9236.6
## &lt;none&gt;                     2685757  9238.5
## - income      1      5544  2691301  9238.9
## - afam        1      6479  2692237  9239.3
## - male        1     18570  2704327  9244.6
## - population  1     24029  2709786  9247.0
## - law         1     26389  2712146  9248.0
## - prisoners   1    303717  2989474  9362.2
## - murder      1    336617  3022375  9375.0
## - year       22    502244  3188001  9395.6
## - robbery     1   3058367  5744124 10128.2
## - state      50   9307137 11992894 10893.7
## 
## Step:  AIC=9236.6
## violent ~ year + murder + robbery + prisoners + afam + male + 
##     population + income + state + law
## 
##              Df Sum of Sq      RSS     AIC
## &lt;none&gt;                     2685976  9236.6
## - income      1      5838  2691814  9237.2
## - afam        1     16775  2702751  9241.9
## - law         1     26764  2712740  9246.2
## - male        1     27232  2713208  9246.4
## - population  1     27239  2713215  9246.4
## - prisoners   1    303511  2989487  9360.2
## - murder      1    336791  3022767  9373.2
## - year       22    527892  3213868  9403.1
## - robbery     1   3136507  5822483 10142.1
## - state      50  10803349 13489325 11029.7
</code></pre>

<ul>
<li>We transform cauc to a log(cauc)

<ul>
<li>After running the linear model we now run the Stepwise Regression</li>
<li>The Stepwise regression ended up still removing cauc so we will disregard this model</li>
</ul></li>
</ul>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Cross-Validation for Linear Models</h2>
  <p><img src="figure/fig10-1.png" alt="plot of chunk fig10"></p>

</section>
<section class='class' data-state='' id='Slide'>
  <h2>Cross-Validation for Linear Models against 10 seeds each</h2>
  <p><img src="figure/fig.show:(%22animate%22" alt="plot of chunk fig.show:(&quot;animate&quot;)">-1.png)</p>

<p><img src="figure/fig.show:(%22animate%22" alt="plot of chunk fig.show:(&quot;animate&quot;)">-2.png)</p>

<p><img src="figure/fig.show:(%22animate%22" alt="plot of chunk fig.show:(&quot;animate&quot;)">-3.png)</p>

<p><img src="figure/fig.show:(%22animate%22" alt="plot of chunk fig.show:(&quot;animate&quot;)">-4.png)</p>

<p><img src="figure/fig.show:(%22animate%22" alt="plot of chunk fig.show:(&quot;animate&quot;)">-5.png)</p>

<p><img src="figure/fig.show:(%22animate%22" alt="plot of chunk fig.show:(&quot;animate&quot;)">-6.png)</p>

<p><img src="figure/fig.show:(%22animate%22" alt="plot of chunk fig.show:(&quot;animate&quot;)">-7.png)</p>

<p><img src="figure/fig.show:(%22animate%22" alt="plot of chunk fig.show:(&quot;animate&quot;)">-8.png)</p>

<p><img src="figure/fig.show:(%22animate%22" alt="plot of chunk fig.show:(&quot;animate&quot;)">-9.png)</p>

<p><img src="figure/fig.show:(%22animate%22" alt="plot of chunk fig.show:(&quot;animate&quot;)">-10.png)</p>

</section>
<section class='class' data-state='' id='Slide'>
  <h2><em>Mean Square Error</em></h2>
  <pre><code>##    mse.mOrig   mse.mLog mse.mBCStep  mse.mBC mse.mLogStep
## 1   2889.625 0.01761853    7.150634 7.201197   0.01742300
## 2   2890.438 0.01885826    7.429532 7.645189   0.01815790
## 3   2738.429 0.01737850    6.972956 6.989694   0.01727437
## 4   2859.606 0.01764531    7.123702 7.216332   0.01751542
## 5   2712.441 0.01768070    6.987390 7.057505   0.01731693
## 6   2919.177 0.01747342    7.073046 7.136046   0.01727448
## 7   2933.971 0.01829054    7.059834 7.310023   0.01731601
## 8   2712.441 0.01768070    6.987390 7.057505   0.01731693
## 9   2919.177 0.01747342    7.073046 7.136046   0.01727448
## 10  2933.971 0.01829054    7.059834 7.310023   0.01731601
</code></pre>

<p><strong>MLogStep has the small mean square error</strong>
--- .class #Slide 27</p>

<h2><em>Conclusion</em></h2>

<h1></h1>

<p>Based on the cross-validation model and the Coefficients comparison above we determine that the Log transformation optimized by the Stepwise function is the optimal model</p>

</section>
    </div>
  </div>
</body>
  <script src="libraries/frameworks/revealjs/lib/js/head.min.js"></script>
  <script src="libraries/frameworks/revealjs/js/reveal.min.js"></script>
  <script>
  // Full list of configuration options available here:
  // https://github.com/hakimel/reveal.js#configuration
  Reveal.initialize({
    controls: true,
    progress: true,
    history: true,
    center: true,
    theme: Reveal.getQueryHash().theme || 'default', 
    transition: Reveal.getQueryHash().transition || 'default', 
    dependencies: [
    // Cross-browser shim that fully implements classList -
    // https://github.com/eligrey/classList.js/
      { src: 'libraries/frameworks/revealjs/lib/js/classList.js', condition: function() { return !document.body.classList;}},
      // Zoom in and out with Alt+click
      { src: 'libraries/frameworks/revealjs/plugin/zoom-js/zoom.js', async: true, condition: function() { return !!document.body.classList; } },
      // Speaker notes
      { src: 'libraries/frameworks/revealjs/plugin/notes/notes.js', async: true, condition: function() { return !!document.body.classList; } },
      // Remote control your reveal.js presentation using a touch device
      //{ src: 'libraries/frameworks/revealjs/plugin/remotes/remotes.js', async: true, condition: function() { return !!document.body.classList; } }
      ]
  });
  </script>  <!-- LOAD HIGHLIGHTER JS FILES -->
<script src="libraries/highlighters/highlight.js/highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
<!-- DONE LOADING HIGHLIGHTER JS FILES -->
 

</html>